apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: graviton
spec:
  role: innovate-cluster-karpenter-node
  subnetSelectorTerms:
    - tags:
        Name: "*public*"
  securityGroupSelectorTerms:
    - tags:
        Name: "*node*"
