apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: arm64
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: ami-0db36bcbb6bf68b98
  role: KarpenterNodeRole-innovate-cluster
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: innovate-cluster
        karpenter.sh/az: us-east-1a
    - tags:
        karpenter.sh/discovery: innovate-cluster
        karpenter.sh/az: us-east-1b
    - tags:
        karpenter.sh/discovery: innovate-cluster
        karpenter.sh/az: us-east-1c
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: arm64
spec:
  template:
    spec:
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t4g", "m7g", "c7g"]
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        name: arm64
        kind: EC2NodeClass
        group: karpenter.k8s.aws
      expireAfter: 720h
  limits:
    cpu: 100
